language: python
python:
  - "3.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  # PlatformIO
  - pip install -U platformio

script:
- platformio ci --lib="." --project-option="lib_ignore=Wire" --board=attiny44 --board=attiny84 --board=attiny25 --board=attiny45 --board=attiny85 --board=attiny2313 --board=digispark-pro examples/TestSlave
- platformio ci --lib="." --project-option="lib_ignore=Wire" --board=attiny84 --board=attiny85 --board=digispark-pro examples/TestMaster/TestMaster.ino examples/TestSlave/slave_register.h
- platformio ci --board=uno --board=leonardo examples/TestSlave
- platformio ci --board=uno --board=leonardo examples/TestMaster/TestMaster.ino examples/TestSlave/slave_register.h
